# Uncomment the next line to define a global platform for your project
# platform :ios, '17.6'

target 'PortfolioAppMessages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortfolioAppMessages
#	pod 'FirebaseMessaging'
#	pod 'FirebaseAuth'
#	pod 'FirebaseFirestore'
#	pod 'FirebaseAnalytics'
  
  target 'PortfolioAppMessagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PortfolioAppMessagesUITests' do
    # Pods for testing
  end

end
