# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PortfolioAppMessages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortfolioAppMessages
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  target 'PortfolioAppMessagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PortfolioAppMessagesUITests' do
    # Pods for testing
  end

end
